### ISSUE TITLE
Linux problems - no binary

### ISSUE THREAD

**Issue by brunovianna** [avantcontra/osc-websocket-example#2]
I'm trying to use your fork of websockets for processing but I found some problems. When I replace all the original websockets library files with your zip, a file with same name and different casing is created:

original file: libraries/webSockets.jar
your file: libraries/WebSockets.jar

When I run a server, the sketch only receives String messages, no Binary messages from the js clients. So I assume the library wasn't replaced with your version.

If I erase the original and change the casing on your file, the sketch can't find the library anymore. I'm guessing these are linux issues, with the picky casing?

Any help is welcome.

**Comment by brunovianna** [comment]
I also tried to install it under the sketch folder instead of the processing sketchbook folder but it did't work either.

**Comment by brunovianna** [comment]
I managed to run it after renaming the folder name to WebSockets instead of webSockets inside _libraries_. Ìt has to match the jar file of same name in the _library_ folder

Also the download link on the readme is still pointing to the original zip, it could cause some confusion, https://github.com/avantcontra/processing_websockets.

Thanks for a very useful library!

**Comment by avantcontra** [comment]
@brunovianna Sorry I did not find this issue timely, cause you fixed it so fast.. XD
Thanks for that!
